import * as React from "react";
import Head from 'next/head';
import Gallery from "../components/Gallery"
import { motion } from "framer-motion"

const handleClick = (id) => {
  document.querySelector(id).scrollIntoView({behavior: 'smooth'})
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ziggy Badans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="home" className="justify-center min-h-screen bg-gray-100">
      <div className="flex flex-col items-center justify-center min-h-screen">
        <h1 className="text-5xl font-bold mb-4">Ziggy Badans</h1>
        <p className="text-lg mb-8">Photography & Cinematography</p>
        <div className="grid grid-cols-2 gap-4">
          <button onClick={() => handleClick('#photography')}>
            <div className="bg-white p-4 rounded-lg shadow-md hover:bg-gray-200">
              <h2 className="text-xl font-semibold mb-2">Photography</h2>
              <p>View my photography work.</p>
            </div>
          </button>
          <button onClick={() => handleClick('#cinematography')}>
            <div className="bg-white p-4 rounded-lg shadow-md hover:bg-gray-200">
              <h2 className="text-xl font-semibold mb-2">Cinematography</h2>
              <p>View my cinematography work.</p>
            </div>
          </button>
        </div>
      </div>

      <div id="photography" className="photography flex flex-col items-center min-h-screen">
        <h1 className="text-6xl font-bold mt-12 mb-8">Photography</h1>
        <button onClick={() => handleClick('#home')} className="font-bold text-gray-600 mb-10">Back</button>
        <Gallery></Gallery>
      </div>

      <div id="cinematography" className="min-h-screen">
      <h1 className="text-4xl font-bold mt-12 mb-3">Cinematography</h1>
        <button onClick={() => handleClick('#home')} className="font-bold text-gray-600">Back</button>
      </div>
    </main>
    </div>
  );
}
