import Head from "next/head";
import data from "../data/podcast.json"
import GalleryPodcast from "@/components/GalleryPodcast";

function Podcast() {
    return (
        <div>
            <Head>
                <title>Podcast</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center justify-center min-h-screen">
                <h1 className="text-5xl font-bold mt-20 mb-20">Podcast</h1>
                <div className="grid grid-cols-2 mx-auto">
                    <div className="flex justify-start">
                        <GalleryPodcast jsonFile="/api/podcast.json"/>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Podcast;