import Head from "next/head";
import { useState, useContext } from "react";
import { useRouter } from "next/router";
import { logIn, signUp, auth } from "../../firebaseClient";
import styles from "../styles/SignInForm.module.scss";
import Link from "next/link";

import { UserContext } from "../../hooks/UserContext.Provider";

function SignInForm() {
  const router = useRouter();
  const userContext = useContext(UserContext);

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loginFailed, setLoginFailed] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const userCredential = await logIn({ auth, email, password });
      const user = userCredential.user;
      console.log(user);
      console.log(userContext);
      router.push('/');
    } catch (error) {
      setLoginFailed(true);
      setTimeout(() => setLoginFailed(false), 500);
    }
  };

  const register = async (e) => {
    e.preventDefault();
    
    try {
      await signUp({ auth, email, password });
      alert('User created successfully');
    } catch (error) {
    }
  };

  return (
    <div>
      <Head>
        <title>Ziggy Badans - Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center min-h-screen">
        <form onSubmit={handleSubmit} className={styles.form}>
          <label>
            Email:
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className={loginFailed ? styles.flashAnimation : ""}
            />
          </label>
          <label>
            Password:
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className={loginFailed ? styles.flashAnimation : ""}
            />
          </label>
          <button type="submit">Sign In</button>
          <button onClick={register}>Register</button>
        </form>

        <Link href="/">
          <button className="fixed top-0 left-0 m-4 font-bold">Back</button>
        </Link>
      </main>
    </div>
  );
}

export default SignInForm;
