import { ThemeProvider } from "../interfaces/theme-context";
import Providers from "../interfaces/providers";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <link rel="stylesheet" href="https://use.typekit.net/nub1cfw.css"/>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
      <link href="https://fonts.googleapis.com/css2?family=Days+One&family=Sacramento&display=swap" rel="stylesheet"/>
      <body className="p-0 m-0 overflow-x-hidden">
        <Providers>
          <ThemeProvider>{children}</ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
