import { ThemeProvider } from "../interfaces/ThemeContext";
import Providers from "../interfaces/providers";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="p-0 m-0 overflow-x-hidden">
        <Providers>
          <div className="flex flex-col items-center min-h-screen">
            <ThemeProvider>
              {children}
            </ThemeProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
